# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatMessages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatMessages
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JGProgressHUD'
  pod 'MessageKit'



  target 'chatMessagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chatMessagesUITests' do
    # Pods for testing
  end

end
